### ISSUE TITLE
windows 10 x64 not use exe

### ISSUE THREAD

**Issue by moyuwa** [knownsec/ct#1]

**Comment by moyuwa** [comment]
run error

**Comment by rungobier** [comment]
请提供具体运行截图

**Comment by moyuwa** [comment]
![image](https://user-images.githubusercontent.com/31231318/146474244-c3a3090a-6b7e-441b-b8d4-e025e6438de3.png)

**Comment by rungobier** [comment]
重新编译了一版，你再下载下来运行一下试试？

**Comment by moyuwa** [comment]
it`s ok
