### ISSUE TITLE
error

### ISSUE THREAD

**Issue by im23pds** [knownsec/ct#3]
Start get zoomeye ip data...
thread 'main' panicked at 'The output result is unexpected, please check the permissions.: Error("missing field `error`", line: 1, column: 49198)', src/zoomeye.rs:109:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by im23pds** [comment]
ct -d dict/10w.txt xxx.co
Successfully changed working directory to /tmp/202112221833_xxx.co!
ZoomEye subdomain: 16
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/common.rs:352:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by rungobier** [comment]
路径请设置绝对路径
